# Generated by Django 4.1 on 2023-12-31 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Interface", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Employee",),
    ]
